import JoiDefault, { NumberSchema, Schema } from 'joi';
import dayjs from 'dayjs';

import { GetResourcesConfig } from '../outreach/resource/resource.service';
import { CreateLoadStreamOptions } from '../bigquery.service';

const Joi = JoiDefault.defaults((schema) => {
    if (schema.type === 'number') {
        return (schema as NumberSchema)
            .allow(null)
            .unsafe()
            .custom((value) => (value ? (value as number).toFixed(6) : null));
    }

    return schema.allow(null).allow('');
});

const timestampSchema = Joi.string().custom((value) => {
    const parsed = dayjs(value);
    return parsed.isValid() ? parsed.toISOString() : null;
});

export type Pipeline = {
    getConfig: GetResourcesConfig;
    schema: Schema;
    loadConfig: Omit<CreateLoadStreamOptions, 'dataset'>;
};

export const Account: Pipeline = {
    getConfig: {
        url: '/accounts',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            buyerIntentScore: Joi.number(),
            companyType: Joi.string(),
            custom1: Joi.string(),
            custom2: Joi.string(),
            custom3: Joi.string(),
            custom4: Joi.string(),
            custom5: Joi.string(),
            custom6: Joi.string(),
            custom7: Joi.string(),
            custom8: Joi.string(),
            custom9: Joi.string(),
            custom10: Joi.string(),
            custom11: Joi.string(),
            custom12: Joi.string(),
            custom13: Joi.string(),
            custom14: Joi.string(),
            custom15: Joi.string(),
            custom16: Joi.string(),
            custom17: Joi.string(),
            custom18: Joi.string(),
            custom19: Joi.string(),
            custom20: Joi.string(),
            custom21: Joi.string(),
            custom22: Joi.string(),
            custom23: Joi.string(),
            custom24: Joi.string(),
            custom25: Joi.string(),
            custom26: Joi.string(),
            custom27: Joi.string(),
            custom28: Joi.string(),
            custom29: Joi.string(),
            custom30: Joi.string(),
            custom31: Joi.string(),
            custom32: Joi.string(),
            custom33: Joi.string(),
            custom34: Joi.string(),
            custom35: Joi.string(),
            custom36: Joi.string(),
            custom37: Joi.string(),
            custom38: Joi.string(),
            custom39: Joi.string(),
            custom40: Joi.string(),
            custom41: Joi.string(),
            custom42: Joi.string(),
            custom43: Joi.string(),
            custom44: Joi.string(),
            custom45: Joi.string(),
            custom46: Joi.string(),
            custom47: Joi.string(),
            custom48: Joi.string(),
            custom49: Joi.string(),
            custom50: Joi.string(),
            custom51: Joi.string(),
            custom52: Joi.string(),
            custom53: Joi.string(),
            custom54: Joi.string(),
            custom55: Joi.string(),
            custom56: Joi.string(),
            custom57: Joi.string(),
            custom58: Joi.string(),
            custom59: Joi.string(),
            custom60: Joi.string(),
            custom61: Joi.string(),
            custom62: Joi.string(),
            custom63: Joi.string(),
            custom64: Joi.string(),
            custom65: Joi.string(),
            custom66: Joi.string(),
            custom67: Joi.string(),
            custom68: Joi.string(),
            custom69: Joi.string(),
            custom70: Joi.string(),
            custom71: Joi.string(),
            custom72: Joi.string(),
            custom73: Joi.string(),
            custom74: Joi.string(),
            custom75: Joi.string(),
            custom76: Joi.string(),
            custom77: Joi.string(),
            custom78: Joi.string(),
            custom79: Joi.string(),
            custom80: Joi.string(),
            custom81: Joi.string(),
            custom82: Joi.string(),
            custom83: Joi.string(),
            custom84: Joi.string(),
            custom85: Joi.string(),
            custom86: Joi.string(),
            custom87: Joi.string(),
            custom88: Joi.string(),
            custom89: Joi.string(),
            custom90: Joi.string(),
            custom91: Joi.string(),
            custom92: Joi.string(),
            custom93: Joi.string(),
            custom94: Joi.string(),
            custom95: Joi.string(),
            custom96: Joi.string(),
            custom97: Joi.string(),
            custom98: Joi.string(),
            custom99: Joi.string(),
            custom100: Joi.string(),
            custom101: Joi.string(),
            custom102: Joi.string(),
            custom103: Joi.string(),
            custom104: Joi.string(),
            custom105: Joi.string(),
            custom106: Joi.string(),
            custom107: Joi.string(),
            custom108: Joi.string(),
            custom109: Joi.string(),
            custom110: Joi.string(),
            custom111: Joi.string(),
            custom112: Joi.string(),
            custom113: Joi.string(),
            custom114: Joi.string(),
            custom115: Joi.string(),
            custom116: Joi.string(),
            custom117: Joi.string(),
            custom118: Joi.string(),
            custom119: Joi.string(),
            custom120: Joi.string(),
            custom121: Joi.string(),
            custom122: Joi.string(),
            custom123: Joi.string(),
            custom124: Joi.string(),
            custom125: Joi.string(),
            custom126: Joi.string(),
            custom127: Joi.string(),
            custom128: Joi.string(),
            custom129: Joi.string(),
            custom130: Joi.string(),
            custom131: Joi.string(),
            custom132: Joi.string(),
            custom133: Joi.string(),
            custom134: Joi.string(),
            custom135: Joi.string(),
            custom136: Joi.string(),
            custom137: Joi.string(),
            custom138: Joi.string(),
            custom139: Joi.string(),
            custom140: Joi.string(),
            custom141: Joi.string(),
            custom142: Joi.string(),
            custom143: Joi.string(),
            custom144: Joi.string(),
            custom145: Joi.string(),
            custom146: Joi.string(),
            custom147: Joi.string(),
            custom148: Joi.string(),
            custom149: Joi.string(),
            custom150: Joi.string(),
            createdAt: timestampSchema,
            description: Joi.string(),
            domain: Joi.string(),
            externalSource: Joi.string(),
            followers: Joi.number(),
            foundedAt: timestampSchema,
            industry: Joi.string(),
            linkedInEmployees: Joi.number(),
            linkedInUrl: Joi.string(),
            locality: Joi.string(),
            name: Joi.string(),
            named: Joi.boolean(),
            naturalName: Joi.string(),
            numberOfEmployees: Joi.number(),
            sharingTeamId: Joi.string(),
            touchedAt: timestampSchema,
            updatedAt: timestampSchema,
            websiteUrl: Joi.string(),
        }),
    }),
    loadConfig: {
        table: 'Account',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'buyerIntentScore', type: 'NUMERIC' },
                    { name: 'companyType', type: 'STRING' },
                    { name: 'custom1', type: 'STRING' },
                    { name: 'custom2', type: 'STRING' },
                    { name: 'custom3', type: 'STRING' },
                    { name: 'custom4', type: 'STRING' },
                    { name: 'custom5', type: 'STRING' },
                    { name: 'custom6', type: 'STRING' },
                    { name: 'custom7', type: 'STRING' },
                    { name: 'custom8', type: 'STRING' },
                    { name: 'custom9', type: 'STRING' },
                    { name: 'custom10', type: 'STRING' },
                    { name: 'custom11', type: 'STRING' },
                    { name: 'custom12', type: 'STRING' },
                    { name: 'custom13', type: 'STRING' },
                    { name: 'custom14', type: 'STRING' },
                    { name: 'custom15', type: 'STRING' },
                    { name: 'custom16', type: 'STRING' },
                    { name: 'custom17', type: 'STRING' },
                    { name: 'custom18', type: 'STRING' },
                    { name: 'custom19', type: 'STRING' },
                    { name: 'custom20', type: 'STRING' },
                    { name: 'custom21', type: 'STRING' },
                    { name: 'custom22', type: 'STRING' },
                    { name: 'custom23', type: 'STRING' },
                    { name: 'custom24', type: 'STRING' },
                    { name: 'custom25', type: 'STRING' },
                    { name: 'custom26', type: 'STRING' },
                    { name: 'custom27', type: 'STRING' },
                    { name: 'custom28', type: 'STRING' },
                    { name: 'custom29', type: 'STRING' },
                    { name: 'custom30', type: 'STRING' },
                    { name: 'custom31', type: 'STRING' },
                    { name: 'custom32', type: 'STRING' },
                    { name: 'custom33', type: 'STRING' },
                    { name: 'custom34', type: 'STRING' },
                    { name: 'custom35', type: 'STRING' },
                    { name: 'custom36', type: 'STRING' },
                    { name: 'custom37', type: 'STRING' },
                    { name: 'custom38', type: 'STRING' },
                    { name: 'custom39', type: 'STRING' },
                    { name: 'custom40', type: 'STRING' },
                    { name: 'custom41', type: 'STRING' },
                    { name: 'custom42', type: 'STRING' },
                    { name: 'custom43', type: 'STRING' },
                    { name: 'custom44', type: 'STRING' },
                    { name: 'custom45', type: 'STRING' },
                    { name: 'custom46', type: 'STRING' },
                    { name: 'custom47', type: 'STRING' },
                    { name: 'custom48', type: 'STRING' },
                    { name: 'custom49', type: 'STRING' },
                    { name: 'custom50', type: 'STRING' },
                    { name: 'custom51', type: 'STRING' },
                    { name: 'custom52', type: 'STRING' },
                    { name: 'custom53', type: 'STRING' },
                    { name: 'custom54', type: 'STRING' },
                    { name: 'custom55', type: 'STRING' },
                    { name: 'custom56', type: 'STRING' },
                    { name: 'custom57', type: 'STRING' },
                    { name: 'custom58', type: 'STRING' },
                    { name: 'custom59', type: 'STRING' },
                    { name: 'custom60', type: 'STRING' },
                    { name: 'custom61', type: 'STRING' },
                    { name: 'custom62', type: 'STRING' },
                    { name: 'custom63', type: 'STRING' },
                    { name: 'custom64', type: 'STRING' },
                    { name: 'custom65', type: 'STRING' },
                    { name: 'custom66', type: 'STRING' },
                    { name: 'custom67', type: 'STRING' },
                    { name: 'custom68', type: 'STRING' },
                    { name: 'custom69', type: 'STRING' },
                    { name: 'custom70', type: 'STRING' },
                    { name: 'custom71', type: 'STRING' },
                    { name: 'custom72', type: 'STRING' },
                    { name: 'custom73', type: 'STRING' },
                    { name: 'custom74', type: 'STRING' },
                    { name: 'custom75', type: 'STRING' },
                    { name: 'custom76', type: 'STRING' },
                    { name: 'custom77', type: 'STRING' },
                    { name: 'custom78', type: 'STRING' },
                    { name: 'custom79', type: 'STRING' },
                    { name: 'custom80', type: 'STRING' },
                    { name: 'custom81', type: 'STRING' },
                    { name: 'custom82', type: 'STRING' },
                    { name: 'custom83', type: 'STRING' },
                    { name: 'custom84', type: 'STRING' },
                    { name: 'custom85', type: 'STRING' },
                    { name: 'custom86', type: 'STRING' },
                    { name: 'custom87', type: 'STRING' },
                    { name: 'custom88', type: 'STRING' },
                    { name: 'custom89', type: 'STRING' },
                    { name: 'custom90', type: 'STRING' },
                    { name: 'custom91', type: 'STRING' },
                    { name: 'custom92', type: 'STRING' },
                    { name: 'custom93', type: 'STRING' },
                    { name: 'custom94', type: 'STRING' },
                    { name: 'custom95', type: 'STRING' },
                    { name: 'custom96', type: 'STRING' },
                    { name: 'custom97', type: 'STRING' },
                    { name: 'custom98', type: 'STRING' },
                    { name: 'custom99', type: 'STRING' },
                    { name: 'custom100', type: 'STRING' },
                    { name: 'custom101', type: 'STRING' },
                    { name: 'custom102', type: 'STRING' },
                    { name: 'custom103', type: 'STRING' },
                    { name: 'custom104', type: 'STRING' },
                    { name: 'custom105', type: 'STRING' },
                    { name: 'custom106', type: 'STRING' },
                    { name: 'custom107', type: 'STRING' },
                    { name: 'custom108', type: 'STRING' },
                    { name: 'custom109', type: 'STRING' },
                    { name: 'custom110', type: 'STRING' },
                    { name: 'custom111', type: 'STRING' },
                    { name: 'custom112', type: 'STRING' },
                    { name: 'custom113', type: 'STRING' },
                    { name: 'custom114', type: 'STRING' },
                    { name: 'custom115', type: 'STRING' },
                    { name: 'custom116', type: 'STRING' },
                    { name: 'custom117', type: 'STRING' },
                    { name: 'custom118', type: 'STRING' },
                    { name: 'custom119', type: 'STRING' },
                    { name: 'custom120', type: 'STRING' },
                    { name: 'custom121', type: 'STRING' },
                    { name: 'custom122', type: 'STRING' },
                    { name: 'custom123', type: 'STRING' },
                    { name: 'custom124', type: 'STRING' },
                    { name: 'custom125', type: 'STRING' },
                    { name: 'custom126', type: 'STRING' },
                    { name: 'custom127', type: 'STRING' },
                    { name: 'custom128', type: 'STRING' },
                    { name: 'custom129', type: 'STRING' },
                    { name: 'custom130', type: 'STRING' },
                    { name: 'custom131', type: 'STRING' },
                    { name: 'custom132', type: 'STRING' },
                    { name: 'custom133', type: 'STRING' },
                    { name: 'custom134', type: 'STRING' },
                    { name: 'custom135', type: 'STRING' },
                    { name: 'custom136', type: 'STRING' },
                    { name: 'custom137', type: 'STRING' },
                    { name: 'custom138', type: 'STRING' },
                    { name: 'custom139', type: 'STRING' },
                    { name: 'custom140', type: 'STRING' },
                    { name: 'custom141', type: 'STRING' },
                    { name: 'custom142', type: 'STRING' },
                    { name: 'custom143', type: 'STRING' },
                    { name: 'custom144', type: 'STRING' },
                    { name: 'custom145', type: 'STRING' },
                    { name: 'custom146', type: 'STRING' },
                    { name: 'custom147', type: 'STRING' },
                    { name: 'custom148', type: 'STRING' },
                    { name: 'custom149', type: 'STRING' },
                    { name: 'custom150', type: 'STRING' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'description', type: 'STRING' },
                    { name: 'domain', type: 'STRING' },
                    { name: 'externalSource', type: 'STRING' },
                    { name: 'followers', type: 'NUMERIC' },
                    { name: 'foundedAt', type: 'TIMESTAMP' },
                    { name: 'industry', type: 'STRING' },
                    { name: 'linkedInEmployees', type: 'NUMERIC' },
                    { name: 'linkedInUrl', type: 'STRING' },
                    { name: 'locality', type: 'STRING' },
                    { name: 'name', type: 'STRING' },
                    { name: 'named', type: 'BOOLEAN' },
                    { name: 'naturalName', type: 'STRING' },
                    { name: 'numberOfEmployees', type: 'NUMERIC' },
                    { name: 'sharingTeamId', type: 'STRING' },
                    { name: 'touchedAt', type: 'TIMESTAMP' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                    { name: 'websiteUrl', type: 'STRING' },
                ],
            },
        ],
    },
};

export const Call: Pipeline = {
    getConfig: {
        url: '/calls',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            answeredAt: timestampSchema,
            completedAt: timestampSchema,
            createdAt: timestampSchema,
            dialedAt: timestampSchema,
            direction: Joi.string(),
            externalVendor: Joi.string(),
            from: Joi.string(),
            note: Joi.string(),
            outcome: Joi.string(),
            recordingUrl: Joi.string(),
            returnedAt: timestampSchema,
            sequenceAction: Joi.string(),
            shouldRecordCall: Joi.boolean(),
            state: Joi.string(),
            stateChangedAt: timestampSchema,
            to: Joi.string(),
            uid: Joi.string(),
            updatedAt: timestampSchema,
            userCallType: Joi.string(),
            vendorCallId: Joi.string(),
            voicemailRecordingUrl: Joi.string(),
        }),
    }),
    loadConfig: {
        table: 'Call',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'answeredAt', type: 'TIMESTAMP' },
                    { name: 'completedAt', type: 'TIMESTAMP' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'dialedAt', type: 'TIMESTAMP' },
                    { name: 'direction', type: 'STRING' },
                    { name: 'externalVendor', type: 'STRING' },
                    { name: 'from', type: 'STRING' },
                    { name: 'note', type: 'STRING' },
                    { name: 'outcome', type: 'STRING' },
                    { name: 'recordingUrl', type: 'STRING' },
                    { name: 'returnedAt', type: 'TIMESTAMP' },
                    { name: 'sequenceAction', type: 'STRING' },
                    { name: 'shouldRecordCall', type: 'BOOLEAN' },
                    { name: 'state', type: 'STRING' },
                    { name: 'stateChangedAt', type: 'TIMESTAMP' },
                    { name: 'to', type: 'STRING' },
                    { name: 'uid', type: 'STRING' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                    { name: 'userCallType', type: 'STRING' },
                    { name: 'vendorCallId', type: 'STRING' },
                    { name: 'voicemailRecordingUrl', type: 'STRING' },
                ],
            },
        ],
    },
};

export const Opportunity: Pipeline = {
    getConfig: {
        url: '/opportunities',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            amount: Joi.number(),
            closeDate: timestampSchema,
            createdAt: timestampSchema,
            currencyType: Joi.string(),
            description: Joi.string(),
            externalCreatedAt: timestampSchema,
            mapLink: Joi.string(),
            mapNextSteps: Joi.string(),
            mapStatus: Joi.string(),
            name: Joi.string(),
            nextStep: Joi.string(),
            opportunityType: Joi.string(),
            probability: Joi.number(),
            prospectingRepId: Joi.string(),
            sharingTeamId: Joi.string(),
            touchedAt: timestampSchema,
            updatedAt: timestampSchema,
        }),
    }),
    loadConfig: {
        table: 'Opportunity',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'amount', type: 'NUMERIC' },
                    { name: 'closeDate', type: 'TIMESTAMP' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'currencyType', type: 'STRING' },
                    { name: 'description', type: 'STRING' },
                    { name: 'externalCreatedAt', type: 'TIMESTAMP' },
                    { name: 'mapLink', type: 'STRING' },
                    { name: 'mapNextSteps', type: 'STRING' },
                    { name: 'mapStatus', type: 'STRING' },
                    { name: 'name', type: 'STRING' },
                    { name: 'nextStep', type: 'STRING' },
                    { name: 'opportunityType', type: 'STRING' },
                    { name: 'probability', type: 'NUMERIC' },
                    { name: 'prospectingRepId', type: 'STRING' },
                    { name: 'sharingTeamId', type: 'STRING' },
                    { name: 'touchedAt', type: 'TIMESTAMP' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                ],
            },
        ],
    },
};

export const OpportunityStage: Pipeline = {
    getConfig: {
        url: '/opportunityStages',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            color: Joi.string(),
            createdAt: timestampSchema,
            isClosed: Joi.boolean(),
            name: Joi.string(),
            order: Joi.number(),
            updatedAt: timestampSchema,
        }),
    }),
    loadConfig: {
        table: 'OpportunityStage',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'color', type: 'STRING' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'isClosed', type: 'BOOLEAN' },
                    { name: 'name', type: 'STRING' },
                    { name: 'order', type: 'NUMERIC' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                ],
            },
        ],
    },
};

export const Prospect: Pipeline = {
    getConfig: {
        url: '/prospects',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            addedAt: timestampSchema,
            addressCity: Joi.string(),
            addressCountry: Joi.string(),
            addressState: Joi.string(),
            addressStreet: Joi.string(),
            addressStreet2: Joi.string(),
            addressZip: Joi.string(),
            angelListUrl: Joi.string(),
            availableAt: timestampSchema,
            callOptedOut: Joi.boolean(),
            callsOptStatus: Joi.string(),
            callsOptedAt: timestampSchema,
            campaignName: Joi.string(),
            clickCount: Joi.number(),
            company: Joi.string(),
            custom1: Joi.string(),
            custom2: Joi.string(),
            custom3: Joi.string(),
            custom4: Joi.string(),
            custom5: Joi.string(),
            custom6: Joi.string(),
            custom7: Joi.string(),
            custom8: Joi.string(),
            custom9: Joi.string(),
            custom10: Joi.string(),
            custom11: Joi.string(),
            custom12: Joi.string(),
            custom13: Joi.string(),
            custom14: Joi.string(),
            custom15: Joi.string(),
            custom16: Joi.string(),
            custom17: Joi.string(),
            custom18: Joi.string(),
            custom19: Joi.string(),
            custom20: Joi.string(),
            custom21: Joi.string(),
            custom22: Joi.string(),
            custom23: Joi.string(),
            custom24: Joi.string(),
            custom25: Joi.string(),
            custom26: Joi.string(),
            custom27: Joi.string(),
            custom28: Joi.string(),
            custom29: Joi.string(),
            custom30: Joi.string(),
            custom31: Joi.string(),
            custom32: Joi.string(),
            custom33: Joi.string(),
            custom34: Joi.string(),
            custom35: Joi.string(),
            custom36: Joi.string(),
            custom37: Joi.string(),
            custom38: Joi.string(),
            custom39: Joi.string(),
            custom40: Joi.string(),
            custom41: Joi.string(),
            custom42: Joi.string(),
            custom43: Joi.string(),
            custom44: Joi.string(),
            custom45: Joi.string(),
            custom46: Joi.string(),
            custom47: Joi.string(),
            custom48: Joi.string(),
            custom49: Joi.string(),
            custom50: Joi.string(),
            custom51: Joi.string(),
            custom52: Joi.string(),
            custom53: Joi.string(),
            custom54: Joi.string(),
            custom55: Joi.string(),
            custom56: Joi.string(),
            custom57: Joi.string(),
            custom58: Joi.string(),
            custom59: Joi.string(),
            custom60: Joi.string(),
            custom61: Joi.string(),
            custom62: Joi.string(),
            custom63: Joi.string(),
            custom64: Joi.string(),
            custom65: Joi.string(),
            custom66: Joi.string(),
            custom67: Joi.string(),
            custom68: Joi.string(),
            custom69: Joi.string(),
            custom70: Joi.string(),
            custom71: Joi.string(),
            custom72: Joi.string(),
            custom73: Joi.string(),
            custom74: Joi.string(),
            custom75: Joi.string(),
            custom76: Joi.string(),
            custom77: Joi.string(),
            custom78: Joi.string(),
            custom79: Joi.string(),
            custom80: Joi.string(),
            custom81: Joi.string(),
            custom82: Joi.string(),
            custom83: Joi.string(),
            custom84: Joi.string(),
            custom85: Joi.string(),
            custom86: Joi.string(),
            custom87: Joi.string(),
            custom88: Joi.string(),
            custom89: Joi.string(),
            custom90: Joi.string(),
            custom91: Joi.string(),
            custom92: Joi.string(),
            custom93: Joi.string(),
            custom94: Joi.string(),
            custom95: Joi.string(),
            custom96: Joi.string(),
            custom97: Joi.string(),
            custom98: Joi.string(),
            custom99: Joi.string(),
            custom100: Joi.string(),
            custom101: Joi.string(),
            custom102: Joi.string(),
            custom103: Joi.string(),
            custom104: Joi.string(),
            custom105: Joi.string(),
            custom106: Joi.string(),
            custom107: Joi.string(),
            custom108: Joi.string(),
            custom109: Joi.string(),
            custom110: Joi.string(),
            custom111: Joi.string(),
            custom112: Joi.string(),
            custom113: Joi.string(),
            custom114: Joi.string(),
            custom115: Joi.string(),
            custom116: Joi.string(),
            custom117: Joi.string(),
            custom118: Joi.string(),
            custom119: Joi.string(),
            custom120: Joi.string(),
            custom121: Joi.string(),
            custom122: Joi.string(),
            custom123: Joi.string(),
            custom124: Joi.string(),
            custom125: Joi.string(),
            custom126: Joi.string(),
            custom127: Joi.string(),
            custom128: Joi.string(),
            custom129: Joi.string(),
            custom130: Joi.string(),
            custom131: Joi.string(),
            custom132: Joi.string(),
            custom133: Joi.string(),
            custom134: Joi.string(),
            custom135: Joi.string(),
            custom136: Joi.string(),
            custom137: Joi.string(),
            custom138: Joi.string(),
            custom139: Joi.string(),
            custom140: Joi.string(),
            custom141: Joi.string(),
            custom142: Joi.string(),
            custom143: Joi.string(),
            custom144: Joi.string(),
            custom145: Joi.string(),
            custom146: Joi.string(),
            custom147: Joi.string(),
            custom148: Joi.string(),
            custom149: Joi.string(),
            custom150: Joi.string(),
            createdAt: timestampSchema,
            dateOfBirth: timestampSchema,
            degree: Joi.string(),
            emailOptedOut: Joi.boolean(),
            emailsOptStatus: Joi.string(),
            emailsOptedAt: timestampSchema,
            engagedAt: timestampSchema,
            engagedScore: Joi.number(),
            eventName: Joi.string(),
            externalId: Joi.string(),
            externalOwner: Joi.string(),
            externalSource: Joi.string(),
            facebookUrl: Joi.string(),
            firstName: Joi.string(),
            gender: Joi.string(),
            githubUrl: Joi.string(),
            githubUsername: Joi.string(),
            googlePlusUrl: Joi.string(),
            graduationDate: timestampSchema,
            jobStartDate: timestampSchema,
            lastName: Joi.string(),
            linkedInConnections: Joi.number(),
            linkedInId: Joi.string(),
            linkedInSlug: Joi.string(),
            linkedInUrl: Joi.string(),
            middleName: Joi.string(),
            name: Joi.string(),
            nickname: Joi.string(),
            occupation: Joi.string(),
            openCount: Joi.number(),
            optedOut: Joi.boolean(),
            optedOutAt: timestampSchema,
            personalNote1: Joi.string(),
            personalNote2: Joi.string(),
            preferredContact: Joi.string(),
            quoraUrl: Joi.string(),
            region: Joi.string(),
            replyCount: Joi.number(),
            school: Joi.string(),
            score: Joi.number(),
            sharingTeamId: Joi.string(),
            source: Joi.string(),
            specialties: Joi.string(),
            stackOverflowId: Joi.string(),
            stackOverflowUrl: Joi.string(),
            timeZone: Joi.string(),
            timeZoneIana: Joi.string(),
            timeZoneInferred: Joi.string(),
            title: Joi.string(),
            touchedAt: timestampSchema,
            trashedAt: timestampSchema,
            twitterUrl: Joi.string(),
            twitterUsername: Joi.string(),
            updatedAt: timestampSchema,
            websiteUrl1: Joi.string(),
            websiteUrl2: Joi.string(),
            websiteUrl3: Joi.string(),
        }),
    }),
    loadConfig: {
        table: 'Prospect',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'addedAt', type: 'TIMESTAMP' },
                    { name: 'addressCity', type: 'STRING' },
                    { name: 'addressCountry', type: 'STRING' },
                    { name: 'addressState', type: 'STRING' },
                    { name: 'addressStreet', type: 'STRING' },
                    { name: 'addressStreet2', type: 'STRING' },
                    { name: 'addressZip', type: 'STRING' },
                    { name: 'angelListUrl', type: 'STRING' },
                    { name: 'availableAt', type: 'TIMESTAMP' },
                    { name: 'callOptedOut', type: 'BOOLEAN' },
                    { name: 'callsOptStatus', type: 'STRING' },
                    { name: 'callsOptedAt', type: 'TIMESTAMP' },
                    { name: 'campaignName', type: 'STRING' },
                    { name: 'clickCount', type: 'NUMERIC' },
                    { name: 'company', type: 'STRING' },
                    { name: 'custom1', type: 'STRING' },
                    { name: 'custom2', type: 'STRING' },
                    { name: 'custom3', type: 'STRING' },
                    { name: 'custom4', type: 'STRING' },
                    { name: 'custom5', type: 'STRING' },
                    { name: 'custom6', type: 'STRING' },
                    { name: 'custom7', type: 'STRING' },
                    { name: 'custom8', type: 'STRING' },
                    { name: 'custom9', type: 'STRING' },
                    { name: 'custom10', type: 'STRING' },
                    { name: 'custom11', type: 'STRING' },
                    { name: 'custom12', type: 'STRING' },
                    { name: 'custom13', type: 'STRING' },
                    { name: 'custom14', type: 'STRING' },
                    { name: 'custom15', type: 'STRING' },
                    { name: 'custom16', type: 'STRING' },
                    { name: 'custom17', type: 'STRING' },
                    { name: 'custom18', type: 'STRING' },
                    { name: 'custom19', type: 'STRING' },
                    { name: 'custom20', type: 'STRING' },
                    { name: 'custom21', type: 'STRING' },
                    { name: 'custom22', type: 'STRING' },
                    { name: 'custom23', type: 'STRING' },
                    { name: 'custom24', type: 'STRING' },
                    { name: 'custom25', type: 'STRING' },
                    { name: 'custom26', type: 'STRING' },
                    { name: 'custom27', type: 'STRING' },
                    { name: 'custom28', type: 'STRING' },
                    { name: 'custom29', type: 'STRING' },
                    { name: 'custom30', type: 'STRING' },
                    { name: 'custom31', type: 'STRING' },
                    { name: 'custom32', type: 'STRING' },
                    { name: 'custom33', type: 'STRING' },
                    { name: 'custom34', type: 'STRING' },
                    { name: 'custom35', type: 'STRING' },
                    { name: 'custom36', type: 'STRING' },
                    { name: 'custom37', type: 'STRING' },
                    { name: 'custom38', type: 'STRING' },
                    { name: 'custom39', type: 'STRING' },
                    { name: 'custom40', type: 'STRING' },
                    { name: 'custom41', type: 'STRING' },
                    { name: 'custom42', type: 'STRING' },
                    { name: 'custom43', type: 'STRING' },
                    { name: 'custom44', type: 'STRING' },
                    { name: 'custom45', type: 'STRING' },
                    { name: 'custom46', type: 'STRING' },
                    { name: 'custom47', type: 'STRING' },
                    { name: 'custom48', type: 'STRING' },
                    { name: 'custom49', type: 'STRING' },
                    { name: 'custom50', type: 'STRING' },
                    { name: 'custom51', type: 'STRING' },
                    { name: 'custom52', type: 'STRING' },
                    { name: 'custom53', type: 'STRING' },
                    { name: 'custom54', type: 'STRING' },
                    { name: 'custom55', type: 'STRING' },
                    { name: 'custom56', type: 'STRING' },
                    { name: 'custom57', type: 'STRING' },
                    { name: 'custom58', type: 'STRING' },
                    { name: 'custom59', type: 'STRING' },
                    { name: 'custom60', type: 'STRING' },
                    { name: 'custom61', type: 'STRING' },
                    { name: 'custom62', type: 'STRING' },
                    { name: 'custom63', type: 'STRING' },
                    { name: 'custom64', type: 'STRING' },
                    { name: 'custom65', type: 'STRING' },
                    { name: 'custom66', type: 'STRING' },
                    { name: 'custom67', type: 'STRING' },
                    { name: 'custom68', type: 'STRING' },
                    { name: 'custom69', type: 'STRING' },
                    { name: 'custom70', type: 'STRING' },
                    { name: 'custom71', type: 'STRING' },
                    { name: 'custom72', type: 'STRING' },
                    { name: 'custom73', type: 'STRING' },
                    { name: 'custom74', type: 'STRING' },
                    { name: 'custom75', type: 'STRING' },
                    { name: 'custom76', type: 'STRING' },
                    { name: 'custom77', type: 'STRING' },
                    { name: 'custom78', type: 'STRING' },
                    { name: 'custom79', type: 'STRING' },
                    { name: 'custom80', type: 'STRING' },
                    { name: 'custom81', type: 'STRING' },
                    { name: 'custom82', type: 'STRING' },
                    { name: 'custom83', type: 'STRING' },
                    { name: 'custom84', type: 'STRING' },
                    { name: 'custom85', type: 'STRING' },
                    { name: 'custom86', type: 'STRING' },
                    { name: 'custom87', type: 'STRING' },
                    { name: 'custom88', type: 'STRING' },
                    { name: 'custom89', type: 'STRING' },
                    { name: 'custom90', type: 'STRING' },
                    { name: 'custom91', type: 'STRING' },
                    { name: 'custom92', type: 'STRING' },
                    { name: 'custom93', type: 'STRING' },
                    { name: 'custom94', type: 'STRING' },
                    { name: 'custom95', type: 'STRING' },
                    { name: 'custom96', type: 'STRING' },
                    { name: 'custom97', type: 'STRING' },
                    { name: 'custom98', type: 'STRING' },
                    { name: 'custom99', type: 'STRING' },
                    { name: 'custom100', type: 'STRING' },
                    { name: 'custom101', type: 'STRING' },
                    { name: 'custom102', type: 'STRING' },
                    { name: 'custom103', type: 'STRING' },
                    { name: 'custom104', type: 'STRING' },
                    { name: 'custom105', type: 'STRING' },
                    { name: 'custom106', type: 'STRING' },
                    { name: 'custom107', type: 'STRING' },
                    { name: 'custom108', type: 'STRING' },
                    { name: 'custom109', type: 'STRING' },
                    { name: 'custom110', type: 'STRING' },
                    { name: 'custom111', type: 'STRING' },
                    { name: 'custom112', type: 'STRING' },
                    { name: 'custom113', type: 'STRING' },
                    { name: 'custom114', type: 'STRING' },
                    { name: 'custom115', type: 'STRING' },
                    { name: 'custom116', type: 'STRING' },
                    { name: 'custom117', type: 'STRING' },
                    { name: 'custom118', type: 'STRING' },
                    { name: 'custom119', type: 'STRING' },
                    { name: 'custom120', type: 'STRING' },
                    { name: 'custom121', type: 'STRING' },
                    { name: 'custom122', type: 'STRING' },
                    { name: 'custom123', type: 'STRING' },
                    { name: 'custom124', type: 'STRING' },
                    { name: 'custom125', type: 'STRING' },
                    { name: 'custom126', type: 'STRING' },
                    { name: 'custom127', type: 'STRING' },
                    { name: 'custom128', type: 'STRING' },
                    { name: 'custom129', type: 'STRING' },
                    { name: 'custom130', type: 'STRING' },
                    { name: 'custom131', type: 'STRING' },
                    { name: 'custom132', type: 'STRING' },
                    { name: 'custom133', type: 'STRING' },
                    { name: 'custom134', type: 'STRING' },
                    { name: 'custom135', type: 'STRING' },
                    { name: 'custom136', type: 'STRING' },
                    { name: 'custom137', type: 'STRING' },
                    { name: 'custom138', type: 'STRING' },
                    { name: 'custom139', type: 'STRING' },
                    { name: 'custom140', type: 'STRING' },
                    { name: 'custom141', type: 'STRING' },
                    { name: 'custom142', type: 'STRING' },
                    { name: 'custom143', type: 'STRING' },
                    { name: 'custom144', type: 'STRING' },
                    { name: 'custom145', type: 'STRING' },
                    { name: 'custom146', type: 'STRING' },
                    { name: 'custom147', type: 'STRING' },
                    { name: 'custom148', type: 'STRING' },
                    { name: 'custom149', type: 'STRING' },
                    { name: 'custom150', type: 'STRING' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'dateOfBirth', type: 'TIMESTAMP' },
                    { name: 'degree', type: 'STRING' },
                    { name: 'emailOptedOut', type: 'BOOLEAN' },
                    { name: 'emailsOptStatus', type: 'STRING' },
                    { name: 'emailsOptedAt', type: 'TIMESTAMP' },
                    { name: 'engagedAt', type: 'TIMESTAMP' },
                    { name: 'engagedScore', type: 'NUMERIC' },
                    { name: 'eventName', type: 'STRING' },
                    { name: 'externalId', type: 'STRING' },
                    { name: 'externalOwner', type: 'STRING' },
                    { name: 'externalSource', type: 'STRING' },
                    { name: 'facebookUrl', type: 'STRING' },
                    { name: 'firstName', type: 'STRING' },
                    { name: 'gender', type: 'STRING' },
                    { name: 'githubUrl', type: 'STRING' },
                    { name: 'githubUsername', type: 'STRING' },
                    { name: 'googlePlusUrl', type: 'STRING' },
                    { name: 'graduationDate', type: 'TIMESTAMP' },
                    { name: 'jobStartDate', type: 'TIMESTAMP' },
                    { name: 'lastName', type: 'STRING' },
                    { name: 'linkedInConnections', type: 'NUMERIC' },
                    { name: 'linkedInId', type: 'STRING' },
                    { name: 'linkedInSlug', type: 'STRING' },
                    { name: 'linkedInUrl', type: 'STRING' },
                    { name: 'middleName', type: 'STRING' },
                    { name: 'name', type: 'STRING' },
                    { name: 'nickname', type: 'STRING' },
                    { name: 'occupation', type: 'STRING' },
                    { name: 'openCount', type: 'NUMERIC' },
                    { name: 'optedOut', type: 'BOOLEAN' },
                    { name: 'optedOutAt', type: 'TIMESTAMP' },
                    { name: 'personalNote1', type: 'STRING' },
                    { name: 'personalNote2', type: 'STRING' },
                    { name: 'preferredContact', type: 'STRING' },
                    { name: 'quoraUrl', type: 'STRING' },
                    { name: 'region', type: 'STRING' },
                    { name: 'replyCount', type: 'NUMERIC' },
                    { name: 'school', type: 'STRING' },
                    { name: 'score', type: 'NUMERIC' },
                    { name: 'sharingTeamId', type: 'STRING' },
                    { name: 'source', type: 'STRING' },
                    { name: 'specialties', type: 'STRING' },
                    { name: 'stackOverflowId', type: 'STRING' },
                    { name: 'stackOverflowUrl', type: 'STRING' },
                    { name: 'timeZone', type: 'STRING' },
                    { name: 'timeZoneIana', type: 'STRING' },
                    { name: 'timeZoneInferred', type: 'STRING' },
                    { name: 'title', type: 'STRING' },
                    { name: 'touchedAt', type: 'TIMESTAMP' },
                    { name: 'trashedAt', type: 'TIMESTAMP' },
                    { name: 'twitterUrl', type: 'STRING' },
                    { name: 'twitterUsername', type: 'STRING' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                    { name: 'websiteUrl1', type: 'STRING' },
                    { name: 'websiteUrl2', type: 'STRING' },
                    { name: 'websiteUrl3', type: 'STRING' },
                ],
            },
        ],
    },
};

export const Sequence: Pipeline = {
    getConfig: {
        url: '/sequences',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            automationPercentage: Joi.number(),
            bounceCount: Joi.number(),
            clickCount: Joi.number(),
            createdAt: timestampSchema,
            deliverCount: Joi.number(),
            description: Joi.string(),
            durationInDays: Joi.number(),
            enabled: Joi.boolean(),
            enabledAt: timestampSchema,
            failureCount: Joi.number(),
            finishOnReply: Joi.boolean(),
            lastUsedAt: timestampSchema,
            locked: Joi.boolean(),
            lockedAt: timestampSchema,
            maxActivations: Joi.number(),
            name: Joi.string(),
            negativeReplyCount: Joi.number(),
            neutralReplyCount: Joi.number(),
            numContactedProspects: Joi.number(),
            numRepliedProspects: Joi.number(),
            openCount: Joi.number(),
            optOutCount: Joi.number(),
            positiveReplyCount: Joi.number(),
            primaryReplyAction: Joi.string(),
            primaryReplyPauseDuration: Joi.number(),
            replyCount: Joi.number(),
            scheduleCount: Joi.number(),
            scheduleIntervalType: Joi.string(),
            secondaryReplyAction: Joi.string(),
            secondaryReplyPauseDuration: Joi.number(),
            sequenceStepCount: Joi.number(),
            sequenceType: Joi.string(),
            shareType: Joi.string(),
            throttleCapacity: Joi.number(),
            throttleMaxAddsPerDay: Joi.number(),
            throttlePaused: Joi.boolean(),
            throttlePausedAt: timestampSchema,
            transactional: Joi.boolean(),
            updatedAt: timestampSchema,
        }),
    }),
    loadConfig: {
        table: 'Sequence',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'automationPercentage', type: 'NUMERIC' },
                    { name: 'bounceCount', type: 'NUMERIC' },
                    { name: 'clickCount', type: 'NUMERIC' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'deliverCount', type: 'NUMERIC' },
                    { name: 'description', type: 'STRING' },
                    { name: 'durationInDays', type: 'NUMERIC' },
                    { name: 'enabled', type: 'BOOLEAN' },
                    { name: 'enabledAt', type: 'TIMESTAMP' },
                    { name: 'failureCount', type: 'NUMERIC' },
                    { name: 'finishOnReply', type: 'BOOLEAN' },
                    { name: 'lastUsedAt', type: 'TIMESTAMP' },
                    { name: 'locked', type: 'BOOLEAN' },
                    { name: 'lockedAt', type: 'TIMESTAMP' },
                    { name: 'maxActivations', type: 'NUMERIC' },
                    { name: 'name', type: 'STRING' },
                    { name: 'negativeReplyCount', type: 'NUMERIC' },
                    { name: 'neutralReplyCount', type: 'NUMERIC' },
                    { name: 'numContactedProspects', type: 'NUMERIC' },
                    { name: 'numRepliedProspects', type: 'NUMERIC' },
                    { name: 'openCount', type: 'NUMERIC' },
                    { name: 'optOutCount', type: 'NUMERIC' },
                    { name: 'positiveReplyCount', type: 'NUMERIC' },
                    { name: 'primaryReplyAction', type: 'STRING' },
                    { name: 'primaryReplyPauseDuration', type: 'NUMERIC' },
                    { name: 'replyCount', type: 'NUMERIC' },
                    { name: 'scheduleCount', type: 'NUMERIC' },
                    { name: 'scheduleIntervalType', type: 'STRING' },
                    { name: 'secondaryReplyAction', type: 'STRING' },
                    { name: 'secondaryReplyPauseDuration', type: 'NUMERIC' },
                    { name: 'sequenceStepCount', type: 'NUMERIC' },
                    { name: 'sequenceType', type: 'STRING' },
                    { name: 'shareType', type: 'STRING' },
                    { name: 'throttleCapacity', type: 'NUMERIC' },
                    { name: 'throttleMaxAddsPerDay', type: 'NUMERIC' },
                    { name: 'throttlePaused', type: 'BOOLEAN' },
                    { name: 'throttlePausedAt', type: 'TIMESTAMP' },
                    { name: 'transactional', type: 'BOOLEAN' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                ],
            },
        ],
    },
};

export const SequenceState: Pipeline = {
    getConfig: {
        url: '/sequenceStates',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        relationships: Joi.object({
            sequence: Joi.object({
                data: Joi.object({
                    id: Joi.number(),
                    type: Joi.string(),
                }),
            }),
        }),
        attributes: Joi.object({
            activeAt: timestampSchema,
            bounceCount: Joi.number(),
            callCompletedAt: timestampSchema,
            clickCount: Joi.number(),
            createdAt: timestampSchema,
            deliverCount: Joi.number(),
            errorReason: Joi.string(),
            failureCount: Joi.number(),
            negativeReplyCount: Joi.number(),
            neutralReplyCount: Joi.number(),
            openCount: Joi.number(),
            optOutCount: Joi.number(),
            pauseReason: Joi.string(),
            positiveReplyCount: Joi.number(),
            repliedAt: timestampSchema,
            replyCount: Joi.number(),
            scheduleCount: Joi.number(),
            state: Joi.string(),
            stateChangedAt: timestampSchema,
            updatedAt: timestampSchema,
        }),
    }),
    loadConfig: {
        table: 'SequenceState',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'relationships',
                type: 'RECORD',
                fields: [
                    {
                        name: 'sequence',
                        type: 'RECORD',
                        fields: [
                            {
                                name: 'data',
                                type: 'RECORD',
                                fields: [
                                    { name: 'id', type: 'NUMERIC' },
                                    { name: 'type', type: 'STRING' },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'activeAt', type: 'TIMESTAMP' },
                    { name: 'bounceCount', type: 'NUMERIC' },
                    { name: 'callCompletedAt', type: 'TIMESTAMP' },
                    { name: 'clickCount', type: 'NUMERIC' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'deliverCount', type: 'NUMERIC' },
                    { name: 'errorReason', type: 'STRING' },
                    { name: 'failureCount', type: 'NUMERIC' },
                    { name: 'negativeReplyCount', type: 'NUMERIC' },
                    { name: 'neutralReplyCount', type: 'NUMERIC' },
                    { name: 'openCount', type: 'NUMERIC' },
                    { name: 'optOutCount', type: 'NUMERIC' },
                    { name: 'pauseReason', type: 'STRING' },
                    { name: 'positiveReplyCount', type: 'NUMERIC' },
                    { name: 'repliedAt', type: 'TIMESTAMP' },
                    { name: 'replyCount', type: 'NUMERIC' },
                    { name: 'scheduleCount', type: 'NUMERIC' },
                    { name: 'state', type: 'STRING' },
                    { name: 'stateChangedAt', type: 'TIMESTAMP' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                ],
            },
        ],
    },
};

export const Template: Pipeline = {
    getConfig: {
        url: '/templates',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            archived: Joi.boolean(),
            archivedAt: timestampSchema,
            bodyHtml: Joi.string(),
            bodyText: Joi.string(),
            bounceCount: Joi.number(),
            clickCount: Joi.number(),
            createdAt: timestampSchema,
            deliverCount: Joi.number(),
            failureCount: Joi.number(),
            lastUsedAt: timestampSchema,
            name: Joi.string(),
            negativeReplyCount: Joi.number(),
            neutralReplyCount: Joi.number(),
            openCount: Joi.number(),
            optOutCount: Joi.number(),
            positiveReplyCount: Joi.number(),
            replyCount: Joi.number(),
            scheduleCount: Joi.number(),
            shareType: Joi.string(),
            subject: Joi.string(),
            trackLinks: Joi.boolean(),
            trackOpens: Joi.boolean(),
            updatedAt: timestampSchema,
        }),
    }),
    loadConfig: {
        table: 'Template',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'archived', type: 'BOOLEAN' },
                    { name: 'archivedAt', type: 'TIMESTAMP' },
                    { name: 'bodyHtml', type: 'STRING' },
                    { name: 'bodyText', type: 'STRING' },
                    { name: 'bounceCount', type: 'NUMERIC' },
                    { name: 'clickCount', type: 'NUMERIC' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'deliverCount', type: 'NUMERIC' },
                    { name: 'failureCount', type: 'NUMERIC' },
                    { name: 'lastUsedAt', type: 'TIMESTAMP' },
                    { name: 'name', type: 'STRING' },
                    { name: 'negativeReplyCount', type: 'NUMERIC' },
                    { name: 'neutralReplyCount', type: 'NUMERIC' },
                    { name: 'openCount', type: 'NUMERIC' },
                    { name: 'optOutCount', type: 'NUMERIC' },
                    { name: 'positiveReplyCount', type: 'NUMERIC' },
                    { name: 'replyCount', type: 'NUMERIC' },
                    { name: 'scheduleCount', type: 'NUMERIC' },
                    { name: 'shareType', type: 'STRING' },
                    { name: 'subject', type: 'STRING' },
                    { name: 'trackLinks', type: 'BOOLEAN' },
                    { name: 'trackOpens', type: 'BOOLEAN' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                ],
            },
        ],
    },
};

export const User: Pipeline = {
    getConfig: {
        url: '/users',
        params: () => ({}),
    },
    schema: Joi.object({
        id: Joi.number(),
        attributes: Joi.object({
            accountsViewId: Joi.number(),
            activityNotificationsDisabled: Joi.boolean(),
            bounceWarningEmailEnabled: Joi.boolean(),
            bridgePhone: Joi.string(),
            bridgePhoneExtension: Joi.string(),
            callsViewId: Joi.number(),
            controlledTabDefault: Joi.string(),
            createdAt: timestampSchema,
            currentSignInAt: timestampSchema,
            dailyDigestEmailEnabled: Joi.boolean(),
            defaultRulesetId: Joi.number(),
            email: Joi.string(),
            enableVoiceRecordings: Joi.boolean(),
            engagementEmailsEnabled: Joi.boolean(),
            firstName: Joi.string(),
            inboundBridgePhone: Joi.string(),
            inboundBridgePhoneExtension: Joi.string(),
            inboundCallBehavior: Joi.string(),
            inboundPhoneType: Joi.string(),
            inboundVoicemailCustomMessageText: Joi.string(),
            inboundVoicemailMessageTextVoice: Joi.string(),
            inboundVoicemailPromptType: Joi.string(),
            kaiaRecordingsViewId: Joi.number(),
            keepBridgePhoneConnected: Joi.boolean(),
            lastName: Joi.string(),
            lastSignInAt: timestampSchema,
            locked: Joi.boolean(),
            mailboxErrorEmailEnabled: Joi.boolean(),
            meetingEngagementNotificationEnabled: Joi.boolean(),
            name: Joi.string(),
            notificationsEnabled: Joi.boolean(),
            oceClickToDialEverywhere: Joi.boolean(),
            oceGmailToolbar: Joi.boolean(),
            oceGmailTrackingState: Joi.string(),
            oceSalesforceEmailDecorating: Joi.boolean(),
            oceSalesforcePhoneDecorating: Joi.boolean(),
            oceUniversalTaskFlow: Joi.boolean(),
            oceWindowMode: Joi.boolean(),
            opportunitiesViewId: Joi.number(),
            passwordExpiresAt: timestampSchema,
            phoneCountryCode: Joi.string(),
            phoneNumber: Joi.string(),
            phoneType: Joi.string(),
            pluginAlertNotificationEnabled: Joi.boolean(),
            preferredVoiceRegion: Joi.string(),
            prefersLocalPresence: Joi.boolean(),
            primaryTimezone: Joi.string(),
            prospectsViewId: Joi.number(),
            reportsTeamPerfViewId: Joi.number(),
            reportsViewId: Joi.number(),
            scimExternalId: Joi.string(),
            scimSource: Joi.string(),
            secondaryTimezone: Joi.string(),
            senderNotificationsExcluded: Joi.boolean(),
            tasksViewId: Joi.number(),
            teamsViewId: Joi.number(),
            tertiaryTimezone: Joi.string(),
            textingEmailNotifications: Joi.boolean(),
            title: Joi.string(),
            unknownReplyEmailEnabled: Joi.boolean(),
            updatedAt: timestampSchema,
            userGuid: Joi.string(),
            username: Joi.string(),
            usersViewId: Joi.number(),
            voicemailNotificationEnabled: Joi.boolean(),
            weeklyDigestEmailEnabled: Joi.boolean(),
        }),
    }),
    loadConfig: {
        table: 'User',
        schema: [
            { name: 'id', type: 'NUMERIC' },
            {
                name: 'attributes',
                type: 'RECORD',
                fields: [
                    { name: 'accountsViewId', type: 'NUMERIC' },
                    { name: 'activityNotificationsDisabled', type: 'BOOLEAN' },
                    { name: 'bounceWarningEmailEnabled', type: 'BOOLEAN' },
                    { name: 'bridgePhone', type: 'STRING' },
                    { name: 'bridgePhoneExtension', type: 'STRING' },
                    { name: 'callsViewId', type: 'NUMERIC' },
                    { name: 'controlledTabDefault', type: 'STRING' },
                    { name: 'createdAt', type: 'TIMESTAMP' },
                    { name: 'currentSignInAt', type: 'TIMESTAMP' },
                    { name: 'dailyDigestEmailEnabled', type: 'BOOLEAN' },
                    { name: 'defaultRulesetId', type: 'NUMERIC' },
                    { name: 'email', type: 'STRING' },
                    { name: 'enableVoiceRecordings', type: 'BOOLEAN' },
                    { name: 'engagementEmailsEnabled', type: 'BOOLEAN' },
                    { name: 'firstName', type: 'STRING' },
                    { name: 'inboundBridgePhone', type: 'STRING' },
                    { name: 'inboundBridgePhoneExtension', type: 'STRING' },
                    { name: 'inboundCallBehavior', type: 'STRING' },
                    { name: 'inboundPhoneType', type: 'STRING' },
                    { name: 'inboundVoicemailCustomMessageText', type: 'STRING' },
                    { name: 'inboundVoicemailMessageTextVoice', type: 'STRING' },
                    { name: 'inboundVoicemailPromptType', type: 'STRING' },
                    { name: 'kaiaRecordingsViewId', type: 'NUMERIC' },
                    { name: 'keepBridgePhoneConnected', type: 'BOOLEAN' },
                    { name: 'lastName', type: 'STRING' },
                    { name: 'lastSignInAt', type: 'TIMESTAMP' },
                    { name: 'locked', type: 'BOOLEAN' },
                    { name: 'mailboxErrorEmailEnabled', type: 'BOOLEAN' },
                    { name: 'meetingEngagementNotificationEnabled', type: 'BOOLEAN' },
                    { name: 'name', type: 'STRING' },
                    { name: 'notificationsEnabled', type: 'BOOLEAN' },
                    { name: 'oceClickToDialEverywhere', type: 'BOOLEAN' },
                    { name: 'oceGmailToolbar', type: 'BOOLEAN' },
                    { name: 'oceGmailTrackingState', type: 'STRING' },
                    { name: 'oceSalesforceEmailDecorating', type: 'BOOLEAN' },
                    { name: 'oceSalesforcePhoneDecorating', type: 'BOOLEAN' },
                    { name: 'oceUniversalTaskFlow', type: 'BOOLEAN' },
                    { name: 'oceWindowMode', type: 'BOOLEAN' },
                    { name: 'opportunitiesViewId', type: 'NUMERIC' },
                    { name: 'passwordExpiresAt', type: 'TIMESTAMP' },
                    { name: 'phoneCountryCode', type: 'STRING' },
                    { name: 'phoneNumber', type: 'STRING' },
                    { name: 'phoneType', type: 'STRING' },
                    { name: 'pluginAlertNotificationEnabled', type: 'BOOLEAN' },
                    { name: 'preferredVoiceRegion', type: 'STRING' },
                    { name: 'prefersLocalPresence', type: 'BOOLEAN' },
                    { name: 'primaryTimezone', type: 'STRING' },
                    { name: 'prospectsViewId', type: 'NUMERIC' },
                    { name: 'reportsTeamPerfViewId', type: 'NUMERIC' },
                    { name: 'reportsViewId', type: 'NUMERIC' },
                    { name: 'scimExternalId', type: 'STRING' },
                    { name: 'scimSource', type: 'STRING' },
                    { name: 'secondaryTimezone', type: 'STRING' },
                    { name: 'senderNotificationsExcluded', type: 'BOOLEAN' },
                    { name: 'tasksViewId', type: 'NUMERIC' },
                    { name: 'teamsViewId', type: 'NUMERIC' },
                    { name: 'tertiaryTimezone', type: 'STRING' },
                    { name: 'textingEmailNotifications', type: 'BOOLEAN' },
                    { name: 'title', type: 'STRING' },
                    { name: 'unknownReplyEmailEnabled', type: 'BOOLEAN' },
                    { name: 'updatedAt', type: 'TIMESTAMP' },
                    { name: 'userGuid', type: 'STRING' },
                    { name: 'username', type: 'STRING' },
                    { name: 'usersViewId', type: 'NUMERIC' },
                    { name: 'voicemailNotificationEnabled', type: 'BOOLEAN' },
                    { name: 'weeklyDigestEmailEnabled', type: 'BOOLEAN' },
                ],
            },
        ],
    },
};
