name: cloud-run

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  GCP_SA: integration-1@nutshell-394011.iam.gserviceaccount.com
  IMAGE: us-docker.pkg.dev/nutshell-394011/docker-1/s2m-outreach:master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ env.IMAGE }}
          push: true

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: echo "PUBLIC_URL=$(gcloud run services describe s2m-outreach-server --region=us-central1 --format='value(status.url)')" >> $GITHUB_ENV

      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: s2m-outreach-server
          image: ${{ env.IMAGE }}
          timeout: 60s
          flags: --args=server
          secrets: |
            OUTREACH_CLIENT_ID=outreach-client-id:latest
            OUTREACH_CLIENT_SECRET=outreach-client-secret:latest
          env_vars: |
            FIRESTORE_DB=master
            PUBLIC_URL=${{ env.PUBLIC_URL }}
